site_name:  Envi OData Public API 1.0
nav:
  - Introduction: index.md
  - Testing with Postman: Testing with Postman.md 
  - Retrieving Data using cURL: Retrieving_Data.md
  - Inventory: Inventory.md
  - Addresses: Addresses.md

theme:
  name: material
  palette: 
    primary: black
  logo: assets/logo.png

use_directory_urls: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
