site_name:  Envi OData Public API 1.0
nav:
  - Topics:
    - Introduction: index.md
    - Testing with Postman: Testing with Postman.md 
    - Retrieving Data Using cURL: Retrieving_Data.md
    - Options and Limitations: Options_and_Limitations.md
    - Custom Options: Custom_Options.md
    - Metadata: Metadata.md
    - Metadata Controlling: Metadata_Controlling.md
    - Rate Limiting: Rate_Limiting.md
    - API Versioning: API_Versioning.md
    - Envi OData Examples: Envi_OData_Examples.md
    - Envi Use Cases: Envi_Use_Cases.md
    - Bi Tool Use Cases: BI_Tool_Use_Cases.md
    - Integrators: Integrators.md
    - GitHub Repositry: GitHub_Repository.md
  - Operations:
    - Authentication: Authentication_POST.md
    - Addresses: Addresses.md
    - AdjustmentItems: AdjustmentItems.md
    - AP Batch: AP_Batch.md
    - Facilities: Facilities.md
    - FuturePricing: FuturePricing.md
    - Inventory: Inventory.md
    - InventoryActivity: InventoryActivity.md
    - InventoryLocations: InventoryLocations.md
    - InventoryLocationsCostAnd <br> Quantity: InventoryLocationsCostAndQuantity.md
    - InventoryLocationsExtended: InventoryLocationsExtended.md
    - InventorySnapshotItems: InventorySnapshotItems.md
    - InventorySnapshots: InventorySnapshots.md
    - InventoryTrackings: InventoryTrackings.md
    - InventoryUOMs: InventoryUOMs.md
    - InventoryVendors: InventoryVendors.md
   
  

theme:
  name: material
  palette: 
    primary: black
  logo: assets/logo.png
  favicon: img/favicon.png
  features:
    - navigation.tabs
    - navigation.top

use_directory_urls: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


extra_css:
  - stylesheets/extra.css
